config/routes.rb
Rails.application.routes.draw do

  get 'book_comments/create'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#index"
  resources :users, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'follows/:user_id' => 'relationships#index'
  get 'followers/:user_id' => 'relationships#show'

  get "/search" => "search#search"

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
   @book = Book.find(params[:book_id])
   favorite = @book.favorites.new(user_id: current_user.id)
   favorite.save
  end

  def destroy
   @book = Book.find(params[:book_id])
   favorite = @book.favorites.find_by(user_id: current_user.id)
   favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true , class: "fas fa-heart heart_blue" %>
 <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");