config/routes.rb
Rails.application.routes.draw do

  get 'book_comments/create'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#index"
  resources :users, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'follows/:user_id' => 'relationships#index'
  get 'followers/:user_id' => 'relationships#show'

  get "/search" => "search#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :book
  has_many :book_comments

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower


  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  attachment :profile_image

  validates :name,
   presence: true,
   uniqueness: true,
   length: { in: 2..20 }

  validates :introduction,
    length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:update]

  def new
    @user = User.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
   if current_user != @user
     redirect_to user_path(current_user.id)
   end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
     render("users/edit")
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_said.html.erb
<!--サイドバー user-->
<div class="mx-auto" style="width: 90%;">
 <h2>User info</h2>
 <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></p>
 <table class="table">
  <tr class="profile-name">
    <td>name</td>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <td>introduction</td>
    <td><%= user.introduction %></td>
  </tr>
    <tr>
    <td>follows</td>
    <td><%= link_to user.follower.count, "follows/:user_id" %></td>
  </tr>
    <tr>
    <td>followers</td>
    <td><%= link_to user.followed.count, 'followers/:user_id' %></td>
  </tr>
</table>
</div>

<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST, type:"button", class:"btn btn-info" %>
  <% else %>
    <%= link_to 'フォローする', follow_path(@user.id), method: :POST, type:"button", class:"btn btn-success" %>
  <% end %>
<% end %>


 <%= link_to edit_user_path(user), class: "btn btn-outline-secondary my-4 col-xs-12", style: "width: 100%;" do %>
   <span class="fas fa-user-cog"></span>
 <% end %>

app/views/users/_search.html.erb
<!-- user.search.html.erb  -->
<div class="col-md-12">
  <table class="table table table-hover">
    <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th> </th>
           <th> </th>
            <th> </th>
             <th> </th>
        </tr>
    </thead>
    <tbody id="user">
    <% users.each do |user| %>
        <tr>
          <td><%= link_to attachment_image_tag user, :profile_image, size:'50x50',fallback: "no_image.jpg" %></td>
          <td><%= user.name  %></td>
          <td>フォロー数：<%= user.follower.count %></td>
          <td>フォロワー数：<%= user.followed.count %></td>
          <td>
           <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          </td>
          <td><%=link_to "Show", user_path(user.id) %></td>
        </tr>
    <% end %>
    </tbody>
</table>
</div>

app/views/users/edit.html.erb
<!--プロフ編集画面-->
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <!-- エラーメッセージ -->
  <% if @user.errors.any? %>
   <%= @user.errors.count %>error prohibited this obj from being saved:
   <% @user.errors.full_messages.each do |message| %>
     <%= message %>
   <% end %>
  <% end %>
  <!-- 編集フォーム -->
  <%= form_with model:@user, local:true do |f| %>
    <label for="inputName">Name</label></br>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></br>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></br>
    <label for="inputImage">Image</label></br>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></br>
    <label for="inputIntroduction">Introduction</label></br>
      <%= f.text_area :introduction, id:"inputIntroduction", placeholder:"自己紹介文"%></br>
      <% if current_user.id == @user.id %>
    <div><%= f.submit "Update User", class: "btn btn-secondary" %></div>
      <% end %>
    <% end %>
   </div>
 </div>
</div>

app/views/users/index.html.erb
<!--Users-->
  <!--エラーメッセージOK-->
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
<div class="container px-5 px-sm-0 mt-3",>
  <div class="row">
    <div class="col-md-3" id="sticky-sidebar">
      <!-- サイドバー  -->
      <%= render 'users/said', user: @user %>
      <%= render 'books/said', book: @book %>
    </div>
    <!-- ユーザー一覧  -->
    <% if user_signed_in? %>
    <div class="col-md-8 offset-md-1">
     <h1>Users</h1>
     <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th> </th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
        <tr>
          <td><%= link_to attachment_image_tag user, :profile_image, size:'50x50',fallback: "no_image.jpg" %></td>
          <td><%= user.name  %></td>
          <td>フォロー数：<%= user.follower.count %></td>
          <td>フォロワー数：<%= user.followed.count %></td>
          <td>
          　<% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          </td>
          <td><%=link_to "Show", user_path(user.id) %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

</div>

app/views/users/show.html.erb
<!--Home /users/id URLOK-->
 <!--エラーメッセージOK-->
 <% if @book.errors.any? %>
   <%= @book.errors.count %>error prohibited this obj from being saved:
   <% @book.errors.full_messages.each do |message| %>
   <%= message %>
    <% end %>
  <% end %>
<div class="container px-5 px-sm-0 mt-3",>
  <div class="row">
    <div class="col-md-3" id="sticky-sidebar">
      <!-- サイドバー  -->
      <%= render 'users/said', user: @user %>
      <%= render 'books/said', book: @book %>
    </div>
    <!--投稿一覧画面-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table table-hover">
        <thead>
          <tr>
            <th> </th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
         <tr>
            <td><%= link_to attachment_image_tag(book.user, :profile_image, size:'50x50',fallback: "no_image.jpg"), user_path(@user.id) %></td>
            <td><%= link_to book.title, book_path(book.id)  %></td>
            <td><%= book.body  %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/users/show_follow.html.erb
<h3>フォロー一覧</h3>
  <% @user.following_user.where.not(id: current_user.id).each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
    </p>
  <% end %>