config/routes.rb
Rails.application.routes.draw do

  get 'book_comments/create'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#index"
  resources :users, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'follows/:user_id' => 'relationships#index'
  get 'followers/:user_id' => 'relationships#show'

  get "/search" => "search#search"

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title,
    presence: true

  validates :body,
    presence: true,
    length: { maximum: 200 }


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
    @favorite = Favorite.new
    @book_comments = BookComment.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @user_a = current_user
    @favorite = Favorite.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if current_user != @book.user
      redirect_to "/books"
    end
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,)
  end

  def correct_user
    user = current_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to users_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_said.html.erb
<!--サイドバー books-->
  <div class="mx-auto" style="width: 90%;">
<!--新規投稿-->
<h1>New book</h1>
<!--投稿フォームOK-->
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <p>Title<p>
    <%= f.text_field :title, style:"width: 100%;" %>
  </div>
  <div class="form-group">
   <p>Opinion</p>
    <%= f.text_area :body, style:"width: 100%;" %></br>
    </div>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>
</div>

app/views/books/_search.html.erb
<!-- book.search.html.erb  -->
<div class="col-md-12">
  <table class="table table table-hover">
    <thead>
        <tr>
            <th> </th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="book">
    <% books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag book.user, :profile_image, size:'50x50',fallback: "no_image.jpg" %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
    </tbody>
</table>
</div>

app/views/books/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/books/edit.html.erb
<!--books/:id/edit-->
<!--サイドバーなし-->
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <!--エラーメッセージ-->
   <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
     <% end %>
   <% end %>
   <%= form_with model: @book, local:true do |f| %>
   <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title, style:"width: 100%;" %>
   </div>
   <div class="form-group">
    <p>Body</p>
    <%= f.text_area :body, style:"width: 100%;" %>
   </div>
   <% if current_user.id == @user.id %>
    <div><%= f.submit 'Update Book' , class: "btn btn-success" %></div>
   <% end %>
   <%= link_to "Show", book_path(@book) %>
    <a>|</a>
   <%= link_to 'Back', books_path %>
   <% end %>
   </div>
 </div>
</div>

app/views/books/index.html.erb
<!-- Books-->
  <!--エラーメッセージOK-->
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
<div class="container px-5 px-sm-0 mt-3",>
  <div class="row">
    <div class="col-md-3" id="sticky-sidebar">
     <!-- サイドバー  -->
     <%= render 'users/said', user: @user %>
     <%= render 'books/said', book: @book %>
    </div>
    <!--投稿一覧画面-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table table-hover">
        <thead>
          <tr>
            <th> </th>
            <th>Title</th>
            <th>Opinion</th>
            <th> </th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
         <tr>
            <td><%= link_to attachment_image_tag(book.user, :profile_image, size:'50x50',fallback: "no_image.jpg"), user_path(book.user_id) %></td>
            <td><%= link_to book.title, book_path(book.id)  %></td>
            <td><%= book.body  %></td>
            <td class="favorite-btn" id="favorites_buttons_<%= book.id %>"><%= render "favorites/favorite", book: book %><%= @favorites_count %></td>
            <td>コメント数:<%= book.book_comments.count %></td>
          </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/books/new.html.erb
<!--  -->

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>件のerrorが発生しました。</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid m-4">
  <div class="row">
    <div class="col-3" id="sticky-sidebar">
     <!-- サイドバー  -->

     <%= render 'books/said', book: @book %>
    </div>
    <div class="col-2"></div>
        <div class="col-7">
        <h2>Books</h2>
     <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th> </th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size:'50x50',fallback: "no_image.jpg" %></td>
          <td><%= user.name  %></td>
          <td><!--link_to 'show' で/users/ID　にとばす--><a href="/">show</a></td>
        </tr>
       <% end %>
      </tbody>
  </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!-- 投稿後の詳細画面books/id  -->

<div class="container px-5 px-sm-0 mt-3",>
  <div class="row">
    <div class="col-md-3" id="sticky-sidebar">
     <!-- サイドバー  -->
     <%= render 'users/said', user: @user %>
     <%= render 'books/said', book: @book_new %>
    </div>
    <!--投稿一覧画面-->
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
     <table class="table">
     <tbody>
       <tr>
         <td><%= link_to user_path(@user) do %>
             <%=  attachment_image_tag @user, :profile_image, size:'50x50',fallback: "no_image.jpg" %>
         <p><%= @book.user.name %></p><% end %></td>
         <td><%= link_to @book.title, book_path(@book) %></td>
         <td><%= @book.body %></td>
         <td class="favorite-btn" id="favorites_buttons_<%= @book.id %>"><%= render "favorites/favorite", book: @book %><%= @favorites_count %></td>
         <td>コメント数:<%= @book.book_comments.count %></td>
         <td><% if current_user.id == @user.id %><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %><% end %></td>
         <td><% if current_user.id == @user.id %><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger", data: { confirm: '本当に消しますか？' } %><% end %></td>
       </tr>
    </tbody>
  </table>
<div id="comments_list_<%= @book.id %>"><%= render "book_comments/comment_list", book: @book_comment %><%= @book_comment_count %></div>
<div id="comments_form_<%= @book.id %>"><%= render "book_comments/book_comment", book: @book_comment %><%= @book_comment_count %></div>
    </div>
  </div>
</div>
</div>